### ISSUE TITLE
Check that models implement CrudModelInterface

### ISSUE THREAD

**Issue by carlosafonso** [carlosafonso/laravel-crud#13]
Given that `CrudController` relies on model classes implementing `CrudModelInterface` (for example for retrieving validation rules) we should check that all models do actually implement said interface.

For example, if `FoosController` relates to model `Foo` but this model does not implement `CrudModelInterface` then the method `getValidationRules()` might not be present, and a fatal error will be raised.

**Comment by carlosafonso** [comment]
We should probably throw an Exception of our own. What are your feelings about this @namelivia ?

**Comment by namelivia** [comment]
Yeah, I think we should proceed like that.
