### ISSUE TITLE
Change default model namespace to App

### ISSUE THREAD

**Issue by carlosafonso** [carlosafonso/laravel-crud#16]
Default L5 installations place all model classes in the `App` namespace. Our package uses a default convention of replacing the `Controllers` part of the controller namespace with `Models`.

Maybe we should simplify this and make it as close as possible to L5 defaults. This way the users of the package will not have to touch anything out of the box.

**Comment by namelivia** [comment]
Yeah, I think that would be better.

**Comment by carlosafonso** [comment]
Done.
