### ISSUE TITLE
Query modifying hooks

### ISSUE THREAD

**Issue by carlosafonso** [carlosafonso/laravel-crud#9]
Some controllers might want to apply additional filtering to a query, but overriding a whole method might be overkill. Hooks could resolve this by passing an instance of QueryBuilder pretty much the same way that scopes work.

**Comment by namelivia** [comment]
Can I have an example of how it is intended to be?

**Comment by carlosafonso** [comment]
Yup.

``` php
public function index()
{
    $q = $this->model->newQuery();
    $q = $this->modifyIndexQuery($q); // example function name
    return $q->paginate(/* ... */);
}

public function modifyIndexQuery($q)
{
    return $q; // default implementation just returns the query
}
```

An extending controller could override `modifyIndexQuery` and apply whichever filters are required on the query, or replace it with a different one.

**Comment by carlosafonso** [comment]
This is already implemented in `index()` and `show()`. Do we need any other query hooks?

**Comment by carlosafonso** [comment]
I'm closing this. We can reopen this issue if we feel we need more query modifiers.
